networks:
  home-network:
    name: home-network

services:

  n8n:
    image: n8nio/n8n:2.4.8
    container_name: n8n
    restart: always
    ports:
      - "8091:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE-false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/home/node/.n8n-files
    networks:
      - home-network
  
  qdrant:
    image: qdrant/qdrant:v1.16
    container_name: qdrant
    hostname: qdrant
    restart: unless-stopped
    ports:
      - "8092:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVIE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__STORAGE_PATH="/qdrant/storage"
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    networks:
      - home-network

volumes:
  n8n_data:
  qdrant_data:
